# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=b' ', verbose_name=b'Top text')),
                ('bot_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=b' ', verbose_name=b'Bot text')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=b'products/%Y/%m/%d', verbose_name=b'Image category')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=b' ', verbose_name=b'Text')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Email Form',
                'verbose_name_plural': 'Email Form',
            },
        ),
        migrations.CreateModel(
            name='HomeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(null=True, upload_to=b'')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home page',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to=b'')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=b' ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to=b'')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Rewiew',
                'verbose_name_plural': 'Rewiew',
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to=b'')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='agro.Topic', verbose_name=b'Topic'),
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together=set([('id', 'slug')]),
        ),
    ]
